server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.115.41.198:3306/weizhiblog?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 981205
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
#      location: D\uploadFiles\temp\
      location: /usr/tmp/uploadFiles/temp/
  redis:
    database: 0
    password: 981205
    port: 6379
    host: 47.115.41.198
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 1000ms
mybatis:
  mapper-locations: classpath*:com/weizhiblog/mapper/*.xml
  type-aliases-package: com.weizhiblog.bean
  configuration:
    map-underscore-to-camel-case: off
logging:
  level:
    root: info
  file:
    name: /usr/tmp/uploadFiles/log/log.log