server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8848
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weizhiblog?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 8848
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      resolve-lazily: false

#  redis:
#    database: 0
#    password: 8848
#    port: 6379
#    host: 47.115.41.198
#    lettuce:
#      pool:
#        min-idle: 5
#        max-idle: 10
#        max-active: 8
#        max-wait: 1ms
#      shutdown-timeout: 1000ms
mybatis:
  mapper-locations: classpath*:com/weizhiblog/mapper/*.xml
  type-aliases-package: com.weizhiblog.bean
  configuration:
    map-underscore-to-camel-case: off
logging:
  level:
    root: info
    com:
      weizhiblog:
        mapper: debug
  file:
    name: /usr/tmp/log/log.log