#服务器配置
server:
  address: localhost
  port: 8081


#mysql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weizhiblog?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 1205
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:com/weizhiblog/mapper/*.xml
  type-aliases-package: com.weizhiblog.bean
  configuration:
    map-underscore-to-camel-case: off

logging:
  level:
    root: info
  file:
    name: backend/src/main/resources/log/my.log